// categorystumps.mjs: every category CAN be stumped. The question is which pattern unlocks it.
//
// A verdict of TOO EASY on a whole category is a category error: it scores the LAZY DEFAULT design
// (the obvious thing the domain vocabulary suggests) and mistakes "the easy way to build this is
// easy" for "this cannot stump". The platform includes these categories because each has a durable
// stump; it just is not the reflex design.
//
// This maps each category to the A..I pattern(s) that make it durable, the lazy trap to avoid, and
// how robust the durable path is (does it survive disclosure). It is the diversity engine: it says
// how to stump ten different slots ten different ways instead of reskinning one.
//
// `lazyDefault` is what our category-level TOO EASY verdicts were actually scoring.
// `durableVia` is the pattern that unlocks it; see stumppatterns.mjs for A..I.
// `robust` is whether that path survives disclosure (D/G/H do; A/B/E/I are delicate).

export const CATEGORY_STUMPS = {
  'Archiving and compression': {
    lazyDefault: 'use the standard decompressor / repair tool -> it errors or round-trips cleanly',
    durableVia: ['D', 'A'],
    sketch: 'an undocumented container whose reflex tool emits confident WRONG bytes; recover the '
      + 'codec behavior from input->output pairs (D), or a latent field that only bites on a record '
      + 'type absent from the sample (A). Grade on a fresh archive so no shipped answer is an oracle.',
    robust: 'partial: D-framed (reconstruct behavior) survives disclosure; a pure latent field does not',
    watch: 'File/Media hands the frame over; keep the crux a decode/repair, not another parity puzzle',
  },
  'Computational Geometry': {
    lazyDefault: 'call a floating-point geometry routine -> confidently wrong under degeneracy',
    durableVia: ['D', 'E'],
    sketch: 'an EXACT predicate (orientation, in-circle, arrangement cell count) where the natural '
      + 'floating approach structurally cannot represent the exact rational answer (D), or a hidden '
      + 'degeneracy (collinear/cocircular) breaks an invariant the reflex assumed (E).',
    robust: 'good: the exact-vs-float gap survives disclosure; float still cannot be exact',
  },
  'NLP and language models': {
    lazyDefault: 'fit or prompt a statistical language model -> cannot represent a formal rule',
    durableVia: ['D'],
    sketch: 'a DETERMINISTIC formal-language rule (a hidden grammar or automaton) framed as language. '
      + 'A statistical LM structurally cannot represent it; only recovering the exact automaton '
      + 'generalizes. This is the fit-trap wearing an NLP costume.',
    robust: 'high: survives disclosure, and it is NOT the finite-field engine, so it adds real range',
    watch: 'grade exact accept/reject on held-out strings; make the sample a characteristic set',
  },
  'Checkpointing and resumption': {
    lazyDefault: 'resume from the checkpoint and continue -> silently diverges',
    durableVia: ['H', 'E'],
    sketch: 'exact bit-identical resumption where the reflex misses a COUPLED piece of hidden state '
      + '(RNG stream position, optimizer moment buffers, dataloader shuffle seed) so the post-resume '
      + 'trajectory diverges (H); or an invariant the resume code assumed is broken by the log (E).',
    robust: 'good: the coupling is hard to get right even when described; this is the unmeasured corner',
  },
  'Algorithms and Optimization theory': {
    lazyDefault: 'apply the memorized template / greedy / LP relaxation -> confident wrong optimum',
    durableVia: ['D', 'G'],
    sketch: 'EXACT optimization on an adversarial instance where the reflex heuristic is confidently '
      + 'suboptimal and verifying optimality is itself intractable, so no cheap self-check exists (D); '
      + 'or many coupled sub-instances under all-or-nothing grading (G). A counting crux works ONLY '
      + 'if the reflex-vs-truth divergence is invisible at every brute-forceable size.',
    robust: 'high for the no-cheap-verify optimization; the naive counting crux is delicate (self-checkable)',
  },
  'Exploit and CTF tasks': {
    lazyDefault: 'run the exploit and see if it pops -> a free success oracle',
    durableVia: ['D', 'F'],
    sketch: 'reconstruct an undocumented protocol / parser behavior from captures (D), rather than a '
      + 'pop-the-shell task whose success self-verifies. Keyed recovery (F) works only if the key is '
      + 'discoverable-in-principle from readable data, else it is unfair.',
    robust: 'medium: avoid the self-verifying exploit; the reconstruct framing survives disclosure',
  },
  'Fine tuning': {
    lazyDefault: 'fine-tune on the data -> smooth loss, fittable, no exact bar',
    durableVia: ['D'],
    sketch: 'recover an EXACT deterministic transformation the "training" data was generated by, where '
      + 'gradient fitting structurally cannot land the exact rule. Hard to make robust and hard to '
      + 'grade exactly; the weakest slot on this list.',
    robust: 'low: fine-tuning invites smoothness; hard to force an exact, disclosure-proof bar',
  },
  'Users Permission and Access control': {
    lazyDefault: 'evaluate each rule in isolation -> wrong on transitive/negative interactions',
    durableVia: ['H'],
    sketch: 'exact effective-permission or reachability over a policy where rules INTERACT: inheritance, '
      + 'denies overriding allows, role revocation resurrecting a superseded grant. Fixing one rule '
      + 'never converges; the difficulty is the coupling, not the count. Survives disclosure.',
    robust: 'high: coupling is hard even when fully described; brand-new category for range',
  },
  'Experiment and metrics analysis': {
    lazyDefault: 'aggregate the visible metric -> misses the latent stratum / as-of correction',
    durableVia: ['A', 'I'],
    sketch: 'an exact result that flips under a latent stratum the sample is homogeneous on (A, a '
      + 'Simpson-style reversal), or a point-in-time correction that only bites on days absent from '
      + 'the sample (I). Delicate: the deciding evidence must be in readable data.',
    robust: 'delicate: opens a data category but must thread discoverable-in-data + unexercised-in-sample',
  },
  'Symbolic computation': {
    lazyDefault: 'fit / approximate the relation -> cannot represent the exact algebraic structure',
    durableVia: ['D'],
    sketch: 'the proven fit-trap: recover an exact relation over a finite field from labeled points; a '
      + 'fitted classifier structurally cannot represent a mod-p surface. Robust and repeatable, but '
      + 'HEAVILY REUSED (8333840, bbb74dc, and more), so it reads as one-trick on probation.',
    robust: 'high but over-used: durable, yet a fourth reskin costs range more than it gains',
  },
};

// Look up how to stump a category, and flag when the durable path is robust vs delicate.
export function howToStump(category) {
  const c = CATEGORY_STUMPS[category];
  if (!c) return { known: false, why: `no mapping for "${category}"; add it as we learn the category` };
  return {
    known: true,
    category,
    lazyDefault: c.lazyDefault,
    durableVia: c.durableVia,
    sketch: c.sketch,
    robust: c.robust,
    watch: c.watch || null,
  };
}

// Rank the categories for a diversity-seeking contributor: robust + new-mechanism + not-overused
// first. `used` is a set of pattern letters already leaned on, so range is rewarded.
export function rankForDiversity(overusedPatterns = new Set(['D'])) {
  const rows = Object.entries(CATEGORY_STUMPS).map(([cat, c]) => {
    const robustScore = c.robust.startsWith('high') ? 2 : c.robust.startsWith('good') ? 1.5
      : c.robust.startsWith('medium') || c.robust.startsWith('partial') ? 1 : 0;
    const freshScore = c.durableVia.some((p) => !overusedPatterns.has(p)) ? 1 : 0;
    return { category: cat, durableVia: c.durableVia, robust: c.robust, score: robustScore + freshScore };
  });
  return rows.sort((a, b) => b.score - a.score);
}
